#ifndef GUARD_CONSTANTS_CUTSCENE_H
#define GUARD_CONSTANTS_CUTSCENE_H

enum Cutscenes
{
    CUTSCENE_TAPUKOKO_BRIDGE,
    CUTSCENE_TAPUKOKO_BRIDGE_SHAKE,
    CUTSCENE_IKITOWN_GET_POKEDEX,
    CUTSCENE_IKITOWN_GIVE_HALA_SPARKLING_STONE,
    CUTSCENE_PLAYERHOUSE_SHOW_MOM_POKEMON,
    CUTSCENE_HAU_GET_STARTER,
    CUTSCENE_COUNT,
};

#endif // GUARD_CONSTANTS_CUTSCENE_H
