#ifndef GUARD_CONSTANTS_CUTSCENE_H
#define GUARD_CONSTANTS_CUTSCENE_H

enum Cutscenes
{
    CUTSCENE_TAPUKOKO_BRIDGE,
    CUTSCENE_TAPUKOKO_BRIDGE_SHAKE,
    CUTSCENE_IKITOWN_GET_POKEDEX,
    CUTSCENE_IKITOWN_GIVE_HALA_SPARKLING_STONE,
    CUTSCENE_PLAYERHOUSE_SHOW_MOM_POKEMON,
    CUTSCENE_HAU_GET_STARTER,
    CUTSCENE_PLAYER_GET_STARTER,
    CUTSCENE_KUKUI_POINTS_TO_IKI,
    CUTSCENE_WELCOME_TO_IKITOWN,
    CUTSCENE_ULTRARECON_INTRO,
    CUTSCENE_IKITOWN_FESTIVAL_BATTLE_1,
    CUTSCENE_IKITOWN_FESTIVAL_BATTLE_2,
    CUTSCENE_IKITOWN_FESTIVAL_BATTLE_3,
    CUTSCENE_IKITOWN_FESTIVAL_BATTLE_4,
    CUTSCENE_ROUTE1_LILLIE_WALK_TO_LAB,
    CUTSCENE_HAUOLI_OUTSKIRTS_LILLIE_OUTSIDE_LAB,
    CUTSCENE_ALOLA_LABORATORY_FIRST_TIME_INTRO,
    CUTSCENE_COUNT,
};

#endif // GUARD_CONSTANTS_CUTSCENE_H
