// Add new IDs here
enum {
    HELP_START_MENU,
    HELP_MEGA_EVOLUTION,
    HELP_MASTER_BALL,
    HELP_GIMMIGHOUL_COINS,
    HELP_ADVENTURE_GUIDE,
    HELP_CATCHING_GUIDE,
    HELP_OVERWORLD_MON_GUIDE,
    HELP_ROTOM_PHONE_GUIDE,
    HELP_NUMBER_OF_MOVES_1,
    HELP_NUMBER_OF_MOVES_2,
    HELP_NUMBER_OF_MOVES_3,
    HELP_CLASSIFICATION_OF_MOVES_1,
    HELP_CLASSIFICATION_OF_MOVES_2,
    HELP_CLASSIFICATION_OF_MOVES_3,
    HELP_CLASSIFICATION_OF_MOVES_4,
    HELP_COUNT
};
