// Add new IDs here
enum {
    HELP_START_MENU,
    HELP_MEGA_EVOLUTION,
    HELP_MASTER_BALL,
    HELP_GIMMIGHOUL_COINS,
    HELP_ADVENTURE_GUIDE,
    HELP_CATCHING_GUIDE,
    HELP_OVERWORLD_MON_GUIDE,
    HELP_COUNT
};
