gText_Birch_Welcome::
	.string "Hey there!\p"
	.string "So the day has finally come that you're\n"
	.string "moving to Alola!\p"
	.string "Alola is a region made up of several\n"
	.string "islands.\p"
	.string "That could be the reason the region is\n"
	.string "chock full of nothin' but rare\l"
	.string "Pokémon, yeah!\p"
	.string "There's no shortage of cool Pokémon\n"
	.string "out here in Alola, either!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Such mysterious creatures!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You'll find 'em all over.\n"
	.string "In the grass, in the caves,\l"
	.string "in the sky and sea…\p"
	.string "Here in Alola we love our Pokémon,\n"
	.string "and we depend on them heaps, too.\p"
	.string "Some of us even battle with 'em, if\n"
	.string "we call ourselves Pokémon Trainers!\p"
	.string "Rockruff! I'll play with you later,\n"
	.string "so cool your jets!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "All right.\p" 
	.string "I gotta ask you some questions\n"
	.string "about yourself so I can introduce\l"
	.string "you to everybody!\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "So which photo should I use for your\n"
	.string "Trainer Passport?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right then, I'll let you\n"
	.string "spell out your name for me.$"

gText_Birch_SoItsPlayer::
	.string "So, you go by {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "10-4, good buddy! I'll let everybody out\n"
	.string "here know you're on your way!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}!\p"
	.string "Yeah, that's a name that hits you like a\n"
	.string "Trop Kick right to the head! Woo!\p"
	.string "Can't wait to see you here in person\n"
	.string "then, cousin!\p"
	.string "$"

gText_Birch_Nameplate::
	.string "Kukui$"
