#ifndef GUARD_UI_SCREENSHOTS
#define GUARD_UI_SCREENSHOTS

#include "main.h"

void Task_OpenScreenshots(u8 taskId);
void Screenshots_Init(MainCallback callback);
void Screenshots_StartMenuInitCB(void);


enum Screenshots
{
    SCREENSHOT_ULTRA_ECLIPSE_LOGO,
    SCREENSHOT_THREE_MONTHS_LATER,
    SCREENSHOT_SURFING_PIKACHU,
    SCREENSHOT_THE_NEXT_DAY,
    SCREENSHOT_ECLIPSE_OUTSIDE_LAB,
    SCREENSHOT_ECLIPSE_OUTSIDE_LAB2,
    SCREENSHOT_ROTOM_PHONE_INTRO_1,
    SCREENSHOT_ROTOM_PHONE_INTRO_2,
    SCREENSHOT_ROTOM_PHONE_INTRO_3,
};

enum ScreenshotFadeModes
{
    SCREENSHOT_FADE_BLACK,
    SCREENSHOT_FADE_WHITE,
};

enum ScreenshotModes
{
    SCREENSHOT_MODE_SINGLE,
    SCREENSHOT_MODE_EXIT_TO_FIELD,
    SCREENSHOT_MODE_SEQUENCE_CONTINUE,
    SCREENSHOT_MODE_SEQUENCE_SETUP,
    SCREENSHOT_MODE_SEQUENCE_END,
};


#endif // GUARD_UI_MENU_H
